### ISSUE TITLE
0.11 fails to start on Win10 WSL2

### ISSUE THREAD

**Issue by poesel** [earthobservations/phenodata#5]
```
markus@Calvin:~$ phenodata
Traceback (most recent call last):
  File "/home/markus/.local/bin/phenodata", line 6, in <module>
    from phenodata.command import run
  File "/home/markus/.local/lib/python2.7/site-packages/phenodata/command.py", line 8, in <module>
    from phenodata.ftp import FTPSession
  File "/home/markus/.local/lib/python2.7/site-packages/phenodata/ftp.py", line 7, in <module>
    import arrow
  File "/home/markus/.local/lib/python2.7/site-packages/arrow/__init__.py", line 3, in <module>
    from .api import get, now, utcnow
  File "/home/markus/.local/lib/python2.7/site-packages/arrow/api.py", line 10, in <module>
    from arrow.factory import ArrowFactory
  File "/home/markus/.local/lib/python2.7/site-packages/arrow/factory.py", line 18, in <module>
    from arrow import parser
  File "/home/markus/.local/lib/python2.7/site-packages/arrow/parser.py", line 15, in <module>
    from backports.functools_lru_cache import lru_cache  # pragma: no cover
ImportError: No module named functools_lru_cache
```

**Comment by amotl** [comment]
Hi there,

thanks for reporting this.

It is sad that this apparently only fails because we used `arrow` to parse the modification date of files on DWD's FTP server. However, from your traceback I can see you are still using Python 2 while you should really be using Python 3 these days.

Please let me know if using Python 3 helps already.

With kind regards,
Andreas.

**Comment by poesel** [comment]
Works with python3. The default in my WSL was still python2.
Thanks Andreas!
